site_name: mkdocstrings-crystal
site_url: "https://oprypin.github.io/mkdocstrings-crystal"
repo_url: "https://github.com/oprypin/mkdocstrings-crystal"
edit_uri: blob/master/docs/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: teal
    accent: purple

extra_css:
  - css/style.css

plugins:
  - search
  - mkdocstrings:
      watch:
        - mkdocstrings
      handlers:
        python:
          selection:
            filters: ["!^_[^_]", "!__new__"]
          rendering:
            show_signature_annotations: true
            show_source: false
            show_root_heading: true
            show_root_full_path: false
  - section-index

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - def_list
  - toc:
      permalink: "#"

nav:
  - Introduction: README.md
  - Quickstart:
    - quickstart/README.md
    - Migrate from `crystal doc`: quickstart/migrate.md
    - Managing Python dependencies: quickstart/python-dependencies.md
    - CI: quickstart/ci.md
  - Configuration: configuration.md
  - Styling: styling.md
  - Extras: extras.md
  - Troubleshooting: troubleshooting.md
  - Introspection API: api.md
  - Showcase: showcase.md
