site_name: MkDocs Plugins
site_url: "https://oprypin.github.io/mkdocstrings-crystal"
repo_url: "https://github.com/oprypin/mkdocstrings-crystal"
edit_uri: blob/master/docs/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: teal
    accent: purple

extra_css:
  - assets/style.css
extra_javascript:
  - assets/script.js

plugins:
  - search
  - section-index
  - mkdocstrings:
      watch:
        - mkdocstrings
      handlers:
        python:
          selection:
            filters: ["!^_[^_]", "!__new__"]
          rendering:
            show_signature_annotations: true
            show_source: false
            show_root_heading: true
            show_root_full_path: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - def_list
  - toc:
      permalink: "#"

nav:
  - mkdocstrings-crystal:
    - README.md
    - Quickstart:
      - quickstart/index.md
      - Migrate from `crystal doc`: quickstart/migrate.md
      - Managing Python dependencies: quickstart/python-dependencies.md
      - Continuous build and publishing: quickstart/ci.md
    - Configuration: configuration.md
    - Styling: styling.md
    - Extras: extras.md
    - Troubleshooting: troubleshooting.md
    - Introspection API: api.md
    - Showcase: showcase.md
  - section-index: /mkdocs-section-index/
  - literate-nav: /mkdocs-literate-nav/
  - gen-files: /mkdocs-gen-files/
  - same-dir: /mkdocs-same-dir/
