site_name: mkdocstrings-crystal
site_url: "https://oprypin.github.io/mkdocstrings-crystal"
repo_url: "https://github.com/oprypin/mkdocstrings-crystal"
edit_uri: blob/master/docs/
use_directory_urls: false

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: teal
    accent: purple

extra_css:
  - css/mkdocstrings.css

plugins:
  - search
  - mkdocstrings:
      watch:
        - mkdocstrings
      handlers:
        python:
          selection:
            filters: ["!^_[^_]", "!__new__"]
          rendering:
            show_signature_annotations: true
            show_source: false
            show_root_heading: true
            show_root_full_path: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: "#"
